---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-store-volsync-ns
spec:
  provider:
    kubernetes:
      remoteNamespace: &namespace storage
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: *namespace
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-volsync
          namespace: *namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-volsync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
rules:
  - apiGroups: [ "" ]
    resources:
      - secrets
    resourceNames:
      - volsync-template
      - volsync-b2-template
      - volsync-mega-template
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-eso-volsync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secrets
subjects:
  - kind: ServiceAccount
    name: eso-volsync
    namespace: storage
