apiVersion: v1
kind: Secret
metadata:
  name: volsync-template
stringData:
  AWS_ACCESS_KEY_ID: "#{ b2_a ccess_key_id }#"
  AWS_SECRET_ACCESS_KEY: "#{ b2_secret_access_key }#"
  RESTIC_PASSWORD: "#{ b2_restic_password }#"
