---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rclone-server
  namespace: storage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :

        containers:
          app:
            image:
              repository: docker.io/rclone/rclone
              tag: 1.71.0@sha256:fd635aecd9667ee3c3bf920d14118090d4f2a83a080c1fa77e0bafbd4587ca87
            args:
              - serve
              - restic
              - -v
              - --addr
              - :8080
              - mega:backups
              - --config
              - /config/rclone.conf
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ "ALL" ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    service:
      app:
        ports:
          http:
            port: 80
            targetPort: 8080

    persistence:
      config:
        type: secret
        name: rclone-config
        globalMounts:
          - path: /config/rclone.conf
            subPath: rclone.conf
